# Generated by Django 4.2.30 on 2026-05-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '关键'), ('success', '成功')], default='info', max_length=20, verbose_name='级别')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='图标')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='键')),
                ('value', models.JSONField(verbose_name='值')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=80, verbose_name='名称')),
                ('region', models.CharField(blank=True, max_length=40, verbose_name='区域')),
                ('description', models.TextField(blank=True, verbose_name='画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('priority', models.IntegerField(default=10, verbose_name='优先级')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='国旗')),
            ],
            options={
                'verbose_name': '目标市场',
                'verbose_name_plural': '目标市场',
                'ordering': ['priority', 'code'],
            },
        ),
    ]
