# Generated by Django 4.2.30 on 2026-05-23 03:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PESTSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='窗口起始')),
                ('period_end', models.DateField(verbose_name='窗口结束')),
                ('target_market', models.CharField(default='global', max_length=60, verbose_name='目标市场')),
                ('political_items', models.JSONField(default=list, verbose_name='政治法律(P)条目')),
                ('economic_items', models.JSONField(default=list, verbose_name='经济(E)条目')),
                ('social_items', models.JSONField(default=list, verbose_name='社会文化(S)条目')),
                ('technological_items', models.JSONField(default=list, verbose_name='技术(T)条目')),
                ('political_summary', models.TextField(blank=True, verbose_name='P 维度洞察')),
                ('economic_summary', models.TextField(blank=True, verbose_name='E 维度洞察')),
                ('social_summary', models.TextField(blank=True, verbose_name='S 维度洞察')),
                ('technological_summary', models.TextField(blank=True, verbose_name='T 维度洞察')),
                ('overall_summary', models.TextField(blank=True, verbose_name='整体宏观环境结论')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PEST 快照',
                'verbose_name_plural': 'PEST 快照',
                'ordering': ['-period_end'],
                'unique_together': {('period_start', 'period_end', 'target_market')},
            },
        ),
        migrations.CreateModel(
            name='StrategicTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='主题')),
                ('description', models.TextField(verbose_name='说明')),
                ('target_market', models.CharField(blank=True, max_length=60, verbose_name='目标市场')),
                ('dimension', models.CharField(blank=True, max_length=20, verbose_name='维度')),
                ('related_info_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='关联情报ID')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='严重度')),
                ('trend', models.CharField(choices=[('rising', '上升'), ('steady', '平稳'), ('declining', '减弱')], default='steady', max_length=20, verbose_name='趋势')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '战略主题',
                'verbose_name_plural': '战略主题',
                'ordering': ['-last_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='窗口起始')),
                ('period_end', models.DateField(verbose_name='窗口结束')),
                ('target_market', models.CharField(default='global', max_length=60, verbose_name='目标市场')),
                ('strengths', models.JSONField(default=list, verbose_name='优势 S')),
                ('weaknesses', models.JSONField(default=list, verbose_name='劣势 W')),
                ('opportunities', models.JSONField(default=list, verbose_name='机会 O')),
                ('threats', models.JSONField(default=list, verbose_name='威胁 T')),
                ('so_strategies', models.TextField(blank=True, verbose_name='SO 增长策略 (优势×机会)')),
                ('st_strategies', models.TextField(blank=True, verbose_name='ST 防御策略 (优势×威胁)')),
                ('wo_strategies', models.TextField(blank=True, verbose_name='WO 扭转策略 (劣势×机会)')),
                ('wt_strategies', models.TextField(blank=True, verbose_name='WT 规避策略 (劣势×威胁)')),
                ('overall_recommendation', models.TextField(blank=True, verbose_name='整体战略建议')),
                ('confidence_score', models.FloatField(default=0.7, verbose_name='置信度(0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pest_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swots', to='analysis.pestsnapshot')),
            ],
            options={
                'verbose_name': 'SWOT 分析',
                'verbose_name_plural': 'SWOT 分析',
                'ordering': ['-period_end'],
            },
        ),
    ]
