# Generated by Django 4.2.30 on 2026-05-23 03:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('period_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('adhoc', '临时')], default='daily', max_length=20, verbose_name='周期')),
                ('period_start', models.DateField(verbose_name='窗口起')),
                ('period_end', models.DateField(verbose_name='窗口止')),
                ('target_market', models.CharField(default='global', max_length=60, verbose_name='目标市场')),
                ('executive_summary', models.TextField(verbose_name='行政摘要')),
                ('key_findings', models.JSONField(default=list, verbose_name='关键发现')),
                ('top_opportunities', models.JSONField(default=list, verbose_name='Top 机会')),
                ('top_risks', models.JSONField(default=list, verbose_name='Top 风险')),
                ('competition_summary', models.TextField(blank=True, verbose_name='竞争维度')),
                ('product_summary', models.TextField(blank=True, verbose_name='产品维度')),
                ('platform_summary', models.TextField(blank=True, verbose_name='平台维度')),
                ('social_summary', models.TextField(blank=True, verbose_name='社媒维度')),
                ('regulation_summary', models.TextField(blank=True, verbose_name='法规维度')),
                ('pest_snapshot_id', models.IntegerField(blank=True, null=True, verbose_name='PEST 快照ID')),
                ('swot_id', models.IntegerField(blank=True, null=True, verbose_name='SWOT ID')),
                ('referenced_info_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='引用情报ID')),
                ('recommended_actions', models.JSONField(default=list, verbose_name='推荐行动项')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('generated_by', models.CharField(default='auto', max_length=40, verbose_name='生成方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '战略简报',
                'verbose_name_plural': '战略简报',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BriefingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('section_key', models.CharField(max_length=40, verbose_name='节键')),
                ('title', models.CharField(max_length=200, verbose_name='小标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('chart_payload', models.JSONField(blank=True, null=True, verbose_name='图表数据')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='briefings.briefing')),
            ],
            options={
                'verbose_name': '简报章节',
                'verbose_name_plural': '简报章节',
                'ordering': ['briefing', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['period_type', '-period_end'], name='briefings_b_period__e9f005_idx'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['status'], name='briefings_b_status_e57dc3_idx'),
        ),
    ]
