# Generated by Django 4.2.30 on 2026-05-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='类别')),
                ('official_url', models.URLField(max_length=500, verbose_name='官方网址')),
                ('list_url', models.URLField(blank=True, max_length=500, verbose_name='信息列表/接口地址')),
                ('source_type', models.CharField(choices=[('api', '免费API'), ('web', '网页爬取'), ('rss', 'RSS/Atom'), ('social', '社交媒体'), ('mixed', '混合')], default='web', max_length=20, verbose_name='类型')),
                ('interface_type', models.CharField(blank=True, max_length=80, verbose_name='接口类型')),
                ('data_format', models.CharField(blank=True, max_length=40, verbose_name='数据格式')),
                ('update_frequency', models.CharField(blank=True, max_length=80, verbose_name='更新频率')),
                ('crawl_method', models.CharField(blank=True, max_length=200, verbose_name='推荐采集方式')),
                ('rate_limit_hint', models.CharField(blank=True, max_length=120, verbose_name='访问频率建议')),
                ('crawl_interval', models.IntegerField(default=3600, verbose_name='爬取间隔(秒)')),
                ('needs_register', models.BooleanField(default=False, verbose_name='是否需注册')),
                ('needs_login', models.BooleanField(default=False, verbose_name='是否需登录')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否付费')),
                ('needs_custom_spider', models.BooleanField(default=True, verbose_name='是否需自编爬虫')),
                ('difficulty', models.IntegerField(choices=[(1, '⭐ 极易'), (2, '⭐⭐ 容易'), (3, '⭐⭐⭐ 中等'), (4, '⭐⭐⭐⭐ 困难'), (5, '⭐⭐⭐⭐⭐ 极难')], default=2, verbose_name='难度')),
                ('priority', models.CharField(choices=[('critical', '🔴 最高'), ('high', '🟠 高'), ('medium', '🟡 中'), ('low', '🟢 低')], default='medium', max_length=20, verbose_name='优先级')),
                ('relevance', models.CharField(blank=True, max_length=120, verbose_name='战略相关度')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('spider_name', models.CharField(blank=True, max_length=120, verbose_name='对应Spider')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='最近抓取时间')),
                ('last_status', models.CharField(blank=True, max_length=20, verbose_name='最近状态')),
                ('last_message', models.TextField(blank=True, verbose_name='最近消息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '信息源',
                'verbose_name_plural': '信息源',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['source_type', 'is_active'], name='sources_inf_source__888718_idx'), models.Index(fields=['priority'], name='sources_inf_priorit_590ca3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_fetched', models.IntegerField(default=0)),
                ('items_new', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='scheduler', max_length=40)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='sources.infosource')),
            ],
            options={
                'verbose_name': '采集任务',
                'verbose_name_plural': '采集任务',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='sources_cra_source__e64736_idx')],
            },
        ),
    ]
