# Generated by Django 4.2.30 on 2026-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosource',
            name='access_tier',
            field=models.CharField(choices=[('free', '免费 (无需注册)'), ('register', '需注册/登录 (免费)'), ('paid', '付费 API')], db_index=True, default='free', max_length=20, verbose_name='访问层级'),
        ),
    ]
