# Generated by Django 4.2.30 on 2026-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=32, verbose_name='链路ID')),
                ('msg_id', models.CharField(max_length=32, unique=True, verbose_name='消息ID')),
                ('msg_type', models.CharField(max_length=80, verbose_name='事件类型')),
                ('sender', models.CharField(blank=True, max_length=60, verbose_name='发送方节点')),
                ('receiver', models.CharField(blank=True, max_length=60, verbose_name='接收方节点')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='载荷')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('output', models.JSONField(blank=True, null=True, verbose_name='输出')),
                ('error', models.TextField(blank=True, verbose_name='错误')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'A2A 消息流水',
                'verbose_name_plural': 'A2A 消息流水',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trace_id', 'created_at'], name='agents_agen_trace_i_927ef2_idx'), models.Index(fields=['msg_type', '-created_at'], name='agents_agen_msg_typ_d7dd96_idx'), models.Index(fields=['status'], name='agents_agen_status_4d4030_idx')],
            },
        ),
    ]
