# Generated by Django 4.2.30 on 2026-05-23 03:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('url', models.URLField(max_length=600, unique=True, verbose_name='原文链接')),
                ('reference_quote', models.TextField(blank=True, verbose_name='原文关键引述')),
                ('language', models.CharField(choices=[('zh', '中文'), ('en', '英文'), ('multi', '多语言')], default='zh', max_length=10, verbose_name='语言')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='原始JSON')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('strategic_dimension', models.CharField(blank=True, choices=[('competition', '竞争'), ('product', '产品'), ('platform', '平台'), ('social', '社媒'), ('regulation', '法规'), ('macro', '宏观经济'), ('industry', '行业报告'), ('other', '其他')], max_length=20, verbose_name='战略维度')),
                ('target_market', models.CharField(blank=True, max_length=60, verbose_name='目标市场')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='国家')),
                ('impact_type', models.CharField(blank=True, choices=[('opportunity', '机会'), ('risk', '风险'), ('watch', '需关注'), ('neutral', '中性')], max_length=20, verbose_name='影响类型')),
                ('severity', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='严重等级')),
                ('impact_score', models.FloatField(blank=True, null=True, verbose_name='影响分数(0-10)')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')], max_length=20, verbose_name='情感倾向')),
                ('pest_type', models.CharField(blank=True, choices=[('P', '政治法律 P'), ('E', '经济 E'), ('S', '社会文化 S'), ('T', '技术 T')], max_length=2, verbose_name='PEST分类')),
                ('opportunity_or_threat', models.CharField(blank=True, choices=[('O', '机会'), ('T', '威胁')], max_length=1, verbose_name='机会/威胁')),
                ('impact_level', models.CharField(blank=True, choices=[('H', '高'), ('M', '中'), ('L', '低')], max_length=1, verbose_name='影响程度')),
                ('impact_rationale', models.TextField(blank=True, verbose_name='LLM判断理由')),
                ('score_relevance', models.FloatField(blank=True, null=True, verbose_name='业务相关度(0-4)')),
                ('score_urgency', models.FloatField(blank=True, null=True, verbose_name='时效紧迫度(0-3)')),
                ('score_authority', models.FloatField(blank=True, null=True, verbose_name='信息权威性(0-2)')),
                ('score_scope', models.FloatField(blank=True, null=True, verbose_name='影响规模(0-1)')),
                ('affected_entities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None, verbose_name='涉及实体')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='标签')),
                ('is_simulated', models.BooleanField(default=False, verbose_name='是否仿真数据')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已LLM分析')),
                ('action_advice', models.TextField(blank=True, verbose_name='行动建议')),
                ('analysis_chain', models.JSONField(blank=True, null=True, verbose_name='LLM分析链')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='sources.infosource')),
            ],
            options={
                'verbose_name': '原始情报',
                'verbose_name_plural': '原始情报',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirmed', '确认'), ('corrected', '修正'), ('ignored', '忽略')], max_length=20, verbose_name='动作')),
                ('correction_note', models.TextField(blank=True, verbose_name='修正说明')),
                ('created_by', models.CharField(default='anonymous', max_length=80, verbose_name='提交人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='intelligence.rawinfo')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rawinfo',
            index=models.Index(fields=['-published_at'], name='intelligenc_publish_9700a6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawinfo',
            index=models.Index(fields=['strategic_dimension', '-published_at'], name='intelligenc_strateg_0c46dc_idx'),
        ),
        migrations.AddIndex(
            model_name='rawinfo',
            index=models.Index(fields=['target_market', '-published_at'], name='intelligenc_target__b1238d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawinfo',
            index=models.Index(fields=['impact_type', '-impact_score'], name='intelligenc_impact__b34e57_idx'),
        ),
        migrations.AddIndex(
            model_name='rawinfo',
            index=models.Index(fields=['pest_type'], name='intelligenc_pest_ty_df9d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawinfo',
            index=models.Index(fields=['is_processed'], name='intelligenc_is_proc_7f1ad1_idx'),
        ),
    ]
