# Generated by Django 4.2.30 on 2026-05-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('feishu_webhook', models.CharField(blank=True, max_length=500, verbose_name='飞书 Webhook')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('role', models.CharField(blank=True, max_length=80, verbose_name='角色')),
                ('subscribe_high_impact', models.BooleanField(default=True, verbose_name='订阅高影响告警')),
                ('subscribe_daily', models.BooleanField(default=True, verbose_name='订阅日报')),
                ('subscribe_weekly', models.BooleanField(default=True, verbose_name='订阅周报')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '通知收件人',
                'verbose_name_plural': '通知收件人',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('channel', models.CharField(choices=[('feishu', '飞书 Webhook'), ('email', '邮件'), ('websocket', '驾驶舱推送'), ('sms', '短信')], max_length=20, verbose_name='通道')),
                ('event_type', models.CharField(choices=[('high_impact_alert', '高影响情报告警'), ('daily_briefing', '每日战略简报'), ('weekly_briefing', '每周战略简报'), ('crawl_failure', '采集失败告警'), ('system', '系统事件')], max_length=40, verbose_name='事件类型')),
                ('subject_tpl', models.CharField(blank=True, max_length=300, verbose_name='标题模板')),
                ('body_tpl', models.TextField(verbose_name='正文模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'ordering': ['channel', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20, verbose_name='通道')),
                ('event_type', models.CharField(max_length=40, verbose_name='事件类型')),
                ('recipient', models.CharField(max_length=300, verbose_name='收件人/接收方')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='主题')),
                ('body', models.TextField(verbose_name='内容')),
                ('ref_model', models.CharField(blank=True, max_length=80, verbose_name='关联模型')),
                ('ref_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '失败'), ('retrying', '重试中')], default='pending', max_length=20, verbose_name='状态')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='返回信息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', '-created_at'], name='notificatio_channel_d7ec6e_idx'), models.Index(fields=['status'], name='notificatio_status_a242db_idx')],
            },
        ),
    ]
