# Generated by Django 4.2.30 on 2026-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='subscribe_opportunity',
            field=models.BooleanField(default=True, verbose_name='订阅机会推送'),
        ),
    ]
