# Generated by Django 4.2.30 on 2026-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_subscribe_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='subscribe_monthly',
            field=models.BooleanField(default=True, verbose_name='订阅月报'),
        ),
    ]
